-- Seed exercise library with common movements
INSERT INTO exercises (name, description, muscle_group, equipment, is_custom) VALUES

-- ============================================================
-- CHEST
-- ============================================================
('Barbell Bench Press', 'Lie on bench, grip bar slightly wider than shoulders, lower to chest, press up.', 'chest', 'barbell', false),
('Dumbbell Bench Press', 'Lie on bench with dumbbells at chest height, press up until arms extended.', 'chest', 'dumbbell', false),
('Incline Barbell Bench Press', 'Set bench to 30-45 degrees, perform bench press with barbell.', 'chest', 'barbell', false),
('Incline Dumbbell Press', 'Set bench to 30-45 degrees, press dumbbells from chest level.', 'chest', 'dumbbell', false),
('Decline Barbell Bench Press', 'Set bench to slight decline, press barbell from lower chest.', 'chest', 'barbell', false),
('Decline Dumbbell Press', 'Set bench to slight decline, press dumbbells from lower chest.', 'chest', 'dumbbell', false),
('Dumbbell Flyes', 'Lie on bench, extend arms with slight bend, lower to sides, squeeze back up.', 'chest', 'dumbbell', false),
('Incline Dumbbell Flyes', 'Set bench to 30-45 degrees, perform flyes with dumbbells.', 'chest', 'dumbbell', false),
('Cable Crossover', 'Stand between cables, bring handles together in front of chest.', 'chest', 'cable', false),
('Low Cable Crossover', 'Set cables low, bring handles up and together in front of chest.', 'chest', 'cable', false),
('Push-ups', 'Hands shoulder-width, lower chest to floor, push back up.', 'chest', 'bodyweight', false),
('Wide Push-ups', 'Hands wider than shoulders, lower chest to floor, push back up.', 'chest', 'bodyweight', false),
('Diamond Push-ups', 'Hands together forming a diamond shape under chest, push up.', 'chest', 'bodyweight', false),
('Decline Push-ups', 'Feet elevated on bench, perform push-ups targeting upper chest.', 'chest', 'bodyweight', false),
('Dips (Chest)', 'Lean forward on parallel bars, lower and press back up.', 'chest', 'bodyweight', false),
('Machine Chest Press', 'Sit in machine, press handles forward until arms extended.', 'chest', 'machine', false),
('Incline Machine Press', 'Sit in incline press machine, press handles forward and up.', 'chest', 'machine', false),
('Pec Deck', 'Sit in machine, bring padded arms together in front of chest.', 'chest', 'machine', false),
('Landmine Press', 'Hold end of barbell at shoulder, press forward and up at an angle.', 'chest', 'barbell', false),
('Svend Press', 'Squeeze two plates together at chest level, press forward and return.', 'chest', 'other', false),
('Floor Press (Barbell)', 'Lie on floor, press barbell from chest level with limited range of motion.', 'chest', 'barbell', false),
('Floor Press (Dumbbell)', 'Lie on floor, press dumbbells from chest level with limited range of motion.', 'chest', 'dumbbell', false),
('Single-Arm Dumbbell Bench Press', 'Lie on bench, press one dumbbell at a time for unilateral work.', 'chest', 'dumbbell', false),
('Cable Chest Press', 'Stand between cables set at chest height, press handles forward.', 'chest', 'cable', false),
('Squeeze Press', 'Press dumbbells together while bench pressing, maintaining inward tension.', 'chest', 'dumbbell', false),

-- ============================================================
-- BACK
-- ============================================================
('Barbell Deadlift', 'Stand over bar, hip-hinge to grip, drive through floor to stand.', 'back', 'barbell', false),
('Sumo Deadlift', 'Wide stance, grip bar between legs, drive hips forward to stand.', 'back', 'barbell', false),
('Rack Pull', 'Deadlift from pins set at or above knee height.', 'back', 'barbell', false),
('Snatch-Grip Deadlift', 'Deadlift with a wide snatch-width grip for upper back emphasis.', 'back', 'barbell', false),
('Barbell Row', 'Hinge forward, pull bar to lower chest/upper abdomen.', 'back', 'barbell', false),
('Pendlay Row', 'Strict barbell row from dead stop on floor each rep.', 'back', 'barbell', false),
('Dumbbell Row', 'One arm on bench, pull dumbbell to hip.', 'back', 'dumbbell', false),
('Kroc Row', 'High-rep heavy single-arm dumbbell row with controlled momentum.', 'back', 'dumbbell', false),
('Chest-Supported Row', 'Lie face down on incline bench, row dumbbells to sides.', 'back', 'dumbbell', false),
('Pull-ups', 'Hang from bar with overhand grip, pull chin above bar.', 'back', 'bodyweight', false),
('Chin-ups', 'Hang from bar with underhand grip, pull chin above bar.', 'back', 'bodyweight', false),
('Neutral-Grip Pull-ups', 'Hang from parallel handles, pull chin above bar.', 'back', 'bodyweight', false),
('Inverted Row', 'Hang under a bar with feet on ground, pull chest to bar.', 'back', 'bodyweight', false),
('Lat Pulldown', 'Sit at machine, pull bar to upper chest.', 'back', 'cable', false),
('Close-Grip Lat Pulldown', 'Sit at machine, pull V-bar handle to upper chest.', 'back', 'cable', false),
('Straight-Arm Pulldown', 'Stand at cable machine, pull bar down with straight arms.', 'back', 'cable', false),
('Seated Cable Row', 'Sit at cable row, pull handle to torso.', 'back', 'cable', false),
('Single-Arm Cable Row', 'Sit or stand at cable, pull one handle to torso.', 'back', 'cable', false),
('Cable Pullover', 'Stand facing cable, pull bar overhead and down to hips with straight arms.', 'back', 'cable', false),
('T-Bar Row', 'Straddle T-bar, pull weight to chest.', 'back', 'barbell', false),
('Meadows Row', 'Stand perpendicular to landmine, row with outside arm.', 'back', 'barbell', false),
('Seal Row', 'Lie face down on elevated bench, row barbell or dumbbells.', 'back', 'barbell', false),
('Machine Row', 'Sit in plate-loaded or selectorized row machine, pull handles to torso.', 'back', 'machine', false),
('Lat Prayer (Machine Pullover)', 'Sit at pullover machine, pull padded bar down in an arc.', 'back', 'machine', false),
('Dumbbell Pullover', 'Lie across bench, lower dumbbell behind head, pull back over chest.', 'back', 'dumbbell', false),
('Kettlebell Gorilla Row', 'Straddle two kettlebells, alternate rowing each side.', 'back', 'kettlebell', false),

-- ============================================================
-- SHOULDERS
-- ============================================================
('Overhead Press', 'Stand with bar at shoulders, press overhead to lockout.', 'shoulders', 'barbell', false),
('Push Press', 'Slight leg drive to help press barbell overhead.', 'shoulders', 'barbell', false),
('Behind-the-Neck Press', 'Press barbell overhead from behind the neck position.', 'shoulders', 'barbell', false),
('Dumbbell Shoulder Press', 'Seated or standing, press dumbbells from shoulders overhead.', 'shoulders', 'dumbbell', false),
('Arnold Press', 'Start with palms facing you, rotate and press overhead.', 'shoulders', 'dumbbell', false),
('Single-Arm Dumbbell Press', 'Press one dumbbell overhead at a time for unilateral work.', 'shoulders', 'dumbbell', false),
('Lateral Raise', 'Stand with dumbbells at sides, raise to shoulder height.', 'shoulders', 'dumbbell', false),
('Cable Lateral Raise', 'Stand sideways to cable, raise handle to shoulder height.', 'shoulders', 'cable', false),
('Machine Lateral Raise', 'Sit in lateral raise machine, raise padded arms to shoulder height.', 'shoulders', 'machine', false),
('Front Raise', 'Stand with dumbbells in front, raise to shoulder height.', 'shoulders', 'dumbbell', false),
('Cable Front Raise', 'Stand facing away from cable, raise handle to shoulder height.', 'shoulders', 'cable', false),
('Plate Front Raise', 'Hold a weight plate with both hands, raise to shoulder height.', 'shoulders', 'other', false),
('Face Pull', 'Pull rope attachment to face level with high elbow position.', 'shoulders', 'cable', false),
('Reverse Flyes', 'Bend forward, raise dumbbells to sides targeting rear delts.', 'shoulders', 'dumbbell', false),
('Cable Reverse Fly', 'Cross cables at chest height, pull handles apart targeting rear delts.', 'shoulders', 'cable', false),
('Rear Delt Machine', 'Sit facing into pec deck machine, push handles apart.', 'shoulders', 'machine', false),
('Upright Row', 'Pull bar or dumbbells up along body to chin height.', 'shoulders', 'barbell', false),
('Dumbbell Upright Row', 'Pull dumbbells up along body to chin height.', 'shoulders', 'dumbbell', false),
('Lu Raise', 'Lateral raise transitioning into a front raise in an L shape.', 'shoulders', 'dumbbell', false),
('Bradford Press', 'Alternately press barbell in front and behind head without full lockout.', 'shoulders', 'barbell', false),
('Landmine Shoulder Press', 'Press end of barbell overhead with one or two arms.', 'shoulders', 'barbell', false),
('Band Pull-Apart', 'Hold band at arms length, pull apart to sides targeting rear delts.', 'shoulders', 'other', false),
('Machine Shoulder Press', 'Sit in shoulder press machine, press handles overhead.', 'shoulders', 'machine', false),
('Z Press', 'Seated on floor with legs extended, press barbell or dumbbells overhead.', 'shoulders', 'barbell', false),
('Kettlebell Halo', 'Circle a kettlebell around your head in both directions.', 'shoulders', 'kettlebell', false),

-- ============================================================
-- LEGS
-- ============================================================
('Barbell Back Squat', 'Bar on upper back, squat to parallel or below, stand back up.', 'legs', 'barbell', false),
('Front Squat', 'Bar on front delts, squat to depth, stand back up.', 'legs', 'barbell', false),
('Box Squat', 'Squat back and down onto a box, pause, then stand.', 'legs', 'barbell', false),
('Zercher Squat', 'Hold barbell in crook of elbows, squat to depth.', 'legs', 'barbell', false),
('Safety Bar Squat', 'Use safety squat bar on upper back, squat to depth.', 'legs', 'barbell', false),
('Pause Squat', 'Back squat with a 2-3 second pause at the bottom.', 'legs', 'barbell', false),
('Romanian Deadlift', 'Slight knee bend, hinge at hips, lower bar along legs.', 'legs', 'barbell', false),
('Dumbbell Romanian Deadlift', 'Slight knee bend, hinge at hips, lower dumbbells along legs.', 'legs', 'dumbbell', false),
('Single-Leg Romanian Deadlift', 'Balance on one leg, hinge forward lowering weight.', 'legs', 'dumbbell', false),
('Stiff-Leg Deadlift', 'Minimal knee bend, hinge at hips keeping legs nearly straight.', 'legs', 'barbell', false),
('Leg Press', 'Sit in machine, push platform away with legs.', 'legs', 'machine', false),
('Single-Leg Press', 'Push leg press platform with one leg at a time.', 'legs', 'machine', false),
('Hack Squat', 'Stand in hack squat machine, squat to depth and press up.', 'legs', 'machine', false),
('V-Squat', 'Stand in V-squat machine, squat to depth with guided path.', 'legs', 'machine', false),
('Pendulum Squat', 'Stand in pendulum squat machine, squat with arc motion.', 'legs', 'machine', false),
('Walking Lunges', 'Step forward into lunge, alternate legs while moving.', 'legs', 'dumbbell', false),
('Reverse Lunges', 'Step backward into lunge, alternate legs.', 'legs', 'dumbbell', false),
('Barbell Reverse Lunge', 'Bar on back, step backward into lunge, alternate legs.', 'legs', 'barbell', false),
('Bulgarian Split Squat', 'Rear foot elevated, squat on front leg.', 'legs', 'dumbbell', false),
('Barbell Bulgarian Split Squat', 'Rear foot elevated, bar on back, squat on front leg.', 'legs', 'barbell', false),
('Step-ups', 'Step onto elevated platform, drive up to standing, step down.', 'legs', 'dumbbell', false),
('Leg Extension', 'Sit in machine, extend legs to straight position.', 'legs', 'machine', false),
('Leg Curl', 'Lie face down, curl weight toward glutes.', 'legs', 'machine', false),
('Seated Leg Curl', 'Sit in machine, curl weight under thighs toward glutes.', 'legs', 'machine', false),
('Nordic Hamstring Curl', 'Kneel with ankles secured, lower torso forward under control.', 'legs', 'bodyweight', false),
('Glute-Ham Raise', 'On GHD, lower torso forward, curl back up using hamstrings.', 'legs', 'machine', false),
('Calf Raise', 'Stand on edge, raise up onto toes, lower slowly.', 'legs', 'machine', false),
('Seated Calf Raise', 'Sit in machine, raise toes pressing against pad.', 'legs', 'machine', false),
('Donkey Calf Raise', 'Hinge forward on platform, raise onto toes with weight on hips.', 'legs', 'machine', false),
('Hip Thrust', 'Upper back on bench, drive hips up with barbell across lap.', 'legs', 'barbell', false),
('Dumbbell Hip Thrust', 'Upper back on bench, drive hips up with dumbbell on lap.', 'legs', 'dumbbell', false),
('Goblet Squat', 'Hold dumbbell at chest, squat to depth.', 'legs', 'dumbbell', false),
('Kettlebell Goblet Squat', 'Hold kettlebell at chest, squat to depth.', 'legs', 'kettlebell', false),
('Adductor Machine', 'Sit in machine, squeeze legs together against resistance.', 'legs', 'machine', false),
('Abductor Machine', 'Sit in machine, push legs apart against resistance.', 'legs', 'machine', false),
('Cable Pull-Through', 'Face away from cable, hinge and pull rope through legs.', 'legs', 'cable', false),
('Belt Squat', 'Weight attached to belt at hips, squat to depth.', 'legs', 'machine', false),
('Sissy Squat', 'Lean back, lower knees forward, extend to standing.', 'legs', 'bodyweight', false),
('Pistol Squat', 'Single-leg squat with non-working leg extended forward.', 'legs', 'bodyweight', false),
('Barbell Good Morning', 'Bar on back, hinge forward at hips, return to standing.', 'legs', 'barbell', false),

-- ============================================================
-- ARMS
-- ============================================================
('Barbell Curl', 'Stand with bar, curl to shoulders keeping elbows fixed.', 'arms', 'barbell', false),
('EZ-Bar Curl', 'Curl EZ-bar to shoulders with angled grip reducing wrist strain.', 'arms', 'barbell', false),
('Dumbbell Curl', 'Alternate or simultaneous curls with dumbbells.', 'arms', 'dumbbell', false),
('Incline Dumbbell Curl', 'Sit on incline bench, curl dumbbells with arms hanging behind torso.', 'arms', 'dumbbell', false),
('Hammer Curl', 'Curl dumbbells with neutral (palms facing) grip.', 'arms', 'dumbbell', false),
('Cross-Body Hammer Curl', 'Curl dumbbell across body toward opposite shoulder.', 'arms', 'dumbbell', false),
('Zottman Curl', 'Curl up with supinated grip, rotate to pronated grip on the way down.', 'arms', 'dumbbell', false),
('Reverse Curl', 'Curl bar with overhand grip targeting brachioradialis.', 'arms', 'barbell', false),
('Spider Curl', 'Lie chest-down on incline bench, curl dumbbells or bar.', 'arms', 'dumbbell', false),
('Concentration Curl', 'Seated, brace elbow on thigh, curl dumbbell.', 'arms', 'dumbbell', false),
('Preacher Curl', 'Curl on preacher bench for strict bicep isolation.', 'arms', 'barbell', false),
('Dumbbell Preacher Curl', 'Single-arm curl on preacher bench with dumbbell.', 'arms', 'dumbbell', false),
('Cable Curl', 'Stand at cable machine, curl bar or handle to shoulders.', 'arms', 'cable', false),
('Bayesian Cable Curl', 'Face away from cable set low, curl with arm behind torso.', 'arms', 'cable', false),
('Machine Bicep Curl', 'Sit in bicep curl machine, curl padded arm toward shoulders.', 'arms', 'machine', false),
('Kettlebell Curl', 'Curl kettlebell with underhand grip.', 'arms', 'kettlebell', false),
('Tricep Pushdown', 'Push cable attachment down until arms extended.', 'arms', 'cable', false),
('Rope Tricep Pushdown', 'Push rope attachment down and apart until arms extended.', 'arms', 'cable', false),
('Overhead Tricep Extension', 'Hold weight overhead, lower behind head, extend.', 'arms', 'dumbbell', false),
('Overhead Cable Extension', 'Face away from cable, extend rope overhead.', 'arms', 'cable', false),
('Close-Grip Bench Press', 'Bench press with hands shoulder-width or narrower.', 'arms', 'barbell', false),
('Skull Crushers', 'Lie on bench, lower bar to forehead, extend arms.', 'arms', 'barbell', false),
('Dumbbell Skull Crushers', 'Lie on bench, lower dumbbells to sides of head, extend arms.', 'arms', 'dumbbell', false),
('Tricep Kickback', 'Hinge forward, extend dumbbell behind you until arm is straight.', 'arms', 'dumbbell', false),
('Cable Kickback', 'Hinge forward at cable machine, extend handle behind you.', 'arms', 'cable', false),
('JM Press', 'Hybrid of close-grip bench and skull crusher, lower bar to chin.', 'arms', 'barbell', false),
('Dips (Triceps)', 'Upright torso on parallel bars, lower and press focusing on triceps.', 'arms', 'bodyweight', false),
('Bench Dips', 'Hands on bench behind you, lower body by bending arms, press up.', 'arms', 'bodyweight', false),
('Machine Tricep Extension', 'Sit in tricep extension machine, press padded arm down.', 'arms', 'machine', false),
('Wrist Curl', 'Forearms on bench, curl bar upward with wrists only.', 'arms', 'barbell', false),
('Reverse Wrist Curl', 'Forearms on bench palms down, extend bar upward with wrists.', 'arms', 'barbell', false),

-- ============================================================
-- CORE
-- ============================================================
('Plank', 'Hold push-up position on forearms, keep body straight.', 'core', 'bodyweight', false),
('Side Plank', 'Lie on one side, hold body straight supported on forearm.', 'core', 'bodyweight', false),
('Copenhagen Plank', 'Side plank with top leg on a bench, bottom leg hanging.', 'core', 'bodyweight', false),
('RKC Plank', 'Plank with maximum full-body tension, elbows slightly forward.', 'core', 'bodyweight', false),
('Hanging Leg Raise', 'Hang from bar, raise legs to parallel or higher.', 'core', 'bodyweight', false),
('Hanging Knee Raise', 'Hang from bar, raise knees toward chest.', 'core', 'bodyweight', false),
('Toes-to-Bar', 'Hang from bar, raise toes all the way to touch the bar.', 'core', 'bodyweight', false),
('Ab Wheel Rollout', 'Kneel with wheel, roll out and return maintaining tight core.', 'core', 'other', false),
('Barbell Rollout', 'Kneel with barbell, roll out and return maintaining tight core.', 'core', 'barbell', false),
('Cable Woodchop', 'Rotate torso pulling cable diagonally across body.', 'core', 'cable', false),
('Cable Crunch', 'Kneel in front of cable, crunch down against resistance.', 'core', 'cable', false),
('Russian Twist', 'Seated with torso angled back, rotate side to side.', 'core', 'bodyweight', false),
('Weighted Russian Twist', 'Seated with torso angled back, rotate side to side holding weight.', 'core', 'dumbbell', false),
('Dead Bug', 'Lie on back, alternate extending opposite arm and leg.', 'core', 'bodyweight', false),
('Pallof Press', 'Stand sideways to cable, press handle forward resisting rotation.', 'core', 'cable', false),
('Crunches', 'Lie on back, curl shoulders toward hips.', 'core', 'bodyweight', false),
('Bicycle Crunch', 'Lie on back, alternate elbow to opposite knee in pedaling motion.', 'core', 'bodyweight', false),
('Decline Sit-ups', 'Hook feet on decline bench, sit up against gravity.', 'core', 'bodyweight', false),
('V-ups', 'Lie flat, simultaneously raise legs and torso to touch toes.', 'core', 'bodyweight', false),
('Hollow Body Hold', 'Lie on back, lift shoulders and legs off floor, hold.', 'core', 'bodyweight', false),
('Dragon Flag', 'Lie on bench, raise body to shoulder blades, lower under control.', 'core', 'bodyweight', false),
('GHD Sit-ups', 'Sit in GHD machine, lower back and sit up explosively.', 'core', 'machine', false),
('Ab Crunch Machine', 'Sit in machine, crunch forward against resistance.', 'core', 'machine', false),
('Farmer Carry', 'Hold heavy weights at sides, walk maintaining upright posture.', 'core', 'dumbbell', false),
('Suitcase Carry', 'Hold heavy weight in one hand, walk maintaining upright posture.', 'core', 'dumbbell', false),
('Overhead Carry', 'Hold weight locked out overhead, walk maintaining stability.', 'core', 'dumbbell', false),
('Turkish Get-up', 'Lie down holding weight overhead, stand up and reverse step by step.', 'core', 'kettlebell', false),
('L-Sit', 'Support body on hands or bars, hold legs parallel to floor.', 'core', 'bodyweight', false),
('Mountain Climbers', 'In push-up position, alternate driving knees toward chest rapidly.', 'core', 'bodyweight', false),

-- ============================================================
-- CARDIO
-- ============================================================
('Treadmill Run', 'Run on treadmill at desired pace and incline.', 'cardio', 'machine', false),
('Treadmill Walk (Incline)', 'Walk on treadmill at steep incline for low-impact cardio.', 'cardio', 'machine', false),
('Rowing Machine', 'Full body cardio on rowing ergometer.', 'cardio', 'machine', false),
('Assault Bike', 'High intensity cycling with arm and leg movement.', 'cardio', 'machine', false),
('Stationary Bike', 'Cycle on stationary bike at desired resistance and cadence.', 'cardio', 'machine', false),
('Recumbent Bike', 'Cycle in reclined position for low-impact cardio.', 'cardio', 'machine', false),
('Elliptical', 'Stride on elliptical machine for low-impact full body cardio.', 'cardio', 'machine', false),
('Stairmaster', 'Climb rotating stairs at desired speed and resistance.', 'cardio', 'machine', false),
('Ski Erg', 'Pull handles down in skiing motion for upper body cardio.', 'cardio', 'machine', false),
('Jump Rope', 'Continuous jumping with rope for cardiovascular conditioning.', 'cardio', 'other', false),
('Double-Under Jump Rope', 'Swing rope under feet twice per jump.', 'cardio', 'other', false),
('Box Jumps', 'Jump onto elevated box, step or jump back down.', 'cardio', 'other', false),
('Burpees', 'Squat, kick back to plank, push-up, jump up.', 'cardio', 'bodyweight', false),
('Battle Ropes', 'Alternate or simultaneous waves with heavy ropes.', 'cardio', 'other', false),
('Kettlebell Swing', 'Hinge and swing kettlebell to shoulder height.', 'cardio', 'kettlebell', false),
('Sled Push', 'Push weighted sled across floor for conditioning.', 'cardio', 'other', false),
('Sled Pull', 'Pull weighted sled toward you using rope or handles.', 'cardio', 'other', false),
('Prowler Push', 'Push prowler sled with low or high handles.', 'cardio', 'other', false),
('High Knees', 'Run in place driving knees to waist height.', 'cardio', 'bodyweight', false),
('Bear Crawl', 'Crawl forward on hands and feet with knees hovering.', 'cardio', 'bodyweight', false),
('Jumping Jacks', 'Jump feet apart while raising arms overhead, return to start.', 'cardio', 'bodyweight', false),
('Sprint Intervals', 'Alternate between maximal sprints and rest periods.', 'cardio', 'bodyweight', false),
('Shuttle Runs', 'Sprint back and forth between two markers.', 'cardio', 'bodyweight', false),
('Farmers Walk', 'Carry heavy weights at sides while walking for distance or time.', 'cardio', 'dumbbell', false);
